"""Make deal_id nullable on deal_documents

Revision ID: 1992a2c8ca49
Revises: 18fdc704c9b4
Create Date: 2025-12-12 20:05:04.639005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1992a2c8ca49'
down_revision: Union[str, None] = '18fdc704c9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal_documents', 'deal_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal_documents', 'deal_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
