"""add_funds_table_and_fund_id_to_deals_and_documents

Revision ID: 372bb9d35aa5
Revises: 1992a2c8ca49
Create Date: 2025-12-13 18:18:55.857473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '372bb9d35aa5'
down_revision: Union[str, None] = '1992a2c8ca49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('target_irr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('target_equity_multiple', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('target_geography', sa.Text(), nullable=True),
    sa.Column('target_asset_types', sa.Text(), nullable=True),
    sa.Column('fund_size', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gp_commitment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('carried_interest', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('preferred_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deal_documents', sa.Column('fund_id', sa.UUID(), nullable=True))
    op.add_column('deal_documents', sa.Column('document_classification', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'deal_documents', 'funds', ['fund_id'], ['id'], ondelete='CASCADE')
    op.add_column('deals', sa.Column('fund_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'deals', 'funds', ['fund_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'fund_id')
    op.drop_constraint(None, 'deal_documents', type_='foreignkey')
    op.drop_column('deal_documents', 'document_classification')
    op.drop_column('deal_documents', 'fund_id')
    op.drop_table('funds')
    # ### end Alembic commands ###
