"""add_our_investment_to_deal_underwriting

Revision ID: 4b7872f51271
Revises: 649c5f5190fd
Create Date: 2026-01-24 17:06:22.551614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7872f51271'
down_revision: Union[str, None] = '649c5f5190fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_underwriting', sa.Column('our_investment', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal_underwriting', 'our_investment')
    # ### end Alembic commands ###
