"""add_geocoding_fields_to_deals

Revision ID: 649c5f5190fd
Revises: a6ff26c3b4fe
Create Date: 2026-01-22 15:24:10.764757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649c5f5190fd'
down_revision: Union[str, None] = 'a6ff26c3b4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deal_documents_timeline', table_name='deal_documents')
    op.drop_index('idx_deal_documents_versions', table_name='deal_documents')
    op.drop_constraint('uq_deal_operator', 'deal_operators', type_='unique')
    op.add_column('deals', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('deals', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('deals', sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deals', sa.Column('msa_source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'msa_source')
    op.drop_column('deals', 'geocoded_at')
    op.drop_column('deals', 'longitude')
    op.drop_column('deals', 'latitude')
    op.create_unique_constraint('uq_deal_operator', 'deal_operators', ['deal_id', 'operator_id'])
    op.create_index('idx_deal_documents_versions', 'deal_documents', ['parent_document_id', 'version_number'], unique=False)
    op.create_index('idx_deal_documents_timeline', 'deal_documents', ['deal_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
